language: bash

notifications:
  email: false

services:
  - docker

before_script:
  - source tango.properties
  - git clone -b ${TANGO_DB_VER} https://github.com/tango-controls/TangoDatabase.git database
  - mkdir -p dbinit
  - cp database/create_db.sql.in dbinit/create_db.sql
  - cp database/create_db_tables.sql.in dbinit/create_db_tables.sql
  - cp database/stored_proc.sql.in dbinit/stored_proc.sql
  - sed -i "s|@TANGO_DB_NAME@|tango|g" dbinit/create_db.sql
  - sed -i "s|@TANGO_DB_NAME@|tango|g" dbinit/create_db_tables.sql
  - sed -i "s|@TANGO_DB_NAME@|tango|g" dbinit/stored_proc.sql
  - sed -i "s|^source create_db_tables.sql$|source /docker-entrypoint-initdb.d/create_db_tables.sql|g" dbinit/create_db.sql
  - sed -i "s|^source stored_proc.sql$|source /docker-entrypoint-initdb.d/stored_proc.sql|g" dbinit/create_db.sql

script:
  - docker build -t tangocs/mysql .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag tangocs/mysql "tangocs/mysql:${TRAVIS_BRANCH}"

deploy:
  - provider: script
    script: docker push "tangocs/mysql:${TRAVIS_BRANCH}"
    on:
      tags: true