language: bash

services:
  - docker

before_script:
  - source tango.properties
  - wget https://github.com/tango-controls/TangoSourceDistribution/releases/download/${TANGO_SOURCE_DISTRIBUTION_VER}/tango-${TANGO_SOURCE_DISTRIBUTION_VER}.tar.gz
  - tar xf tango-${TANGO_SOURCE_DISTRIBUTION_VER}.tar.gz
  - mkdir dbinit
  - cp tango-${TANGO_LIB_VER}/cppserver/database/create_db.sql.in dbinit/create_db.sql
  - cp tango-${TANGO_LIB_VER}/cppserver/database/create_db_tables.sql.in dbinit/include/create_db_tables.sql
  - cp tango-${TANGO_LIB_VER}/cppserver/database/stored_proc.sql.in dbinit/include/stored_proc.sql
  - sed -i "s|@TANGO_DB_NAME@|tango_db|g" dbinit/create_db.sql
  - sed -i "s|@TANGO_DB_NAME@|tango_db|g" dbinit/include/create_db_tables.sql
  - sed -i "s|@TANGO_DB_NAME@|tango_db|g" dbinit/include/stored_proc.sql
  - sed -i "s|^source create_db_tables.sql$|source /docker-entrypoint-initdb.d/include/create_db_tables.sql|g" dbinit/create_db.sql
  - sed -i "s|^source stored_proc.sql$|source /docker-entrypoint-initdb.d/include/stored_proc.sql|g" dbinit/create_db.sql
  - sed -i "/CREATE DATABASE tango_db;/d" dbinit/create_db.sql

script:
  - docker -t tangocs/mysql build .
  